version: '3.1'

services:

  it_tests:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - $PWD:/usr/src/app
    environment:
      MYSQL_HOST: db
      MYSQL_USER: dsy
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: users
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_USER: dsy
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: users
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
