version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_USER: dsy
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: users
    ports:
      - 3306:3306
