version: '3.1'

services:

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_USER: dsy
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: users
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:${PORT}

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_USER: dsy
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: users
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
