name: Dev

on:
  push:
    branches: [main]

jobs:
  build-and-push-docker-mage:
    name: Build docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup SHA
        run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version:  '19.x'

      - run: npm ci
      - run: npm run build --if-present
      - name: run test
        run: make test-it

      - name: Build the Dcoker image
        run: docker build . --file Dockerfile --tag ghcr.io/dsypasit/simple-backend-js:${{env.GITHUB_SHA}}

      - name: Login ghcr.io
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.WORKFLOW_TOKEN }}
          logout: true

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          tags: |
            ghcr.io/dsypasit/workshop:${{ env.GITHUB_SHA }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
